tokens:
  pkeyencryption:
    issuer: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            336134653438386566353033323461383039663263376462393061316266326635396261613837336330636533326
            638333561393661646361386261363836650a66323465323563306333396330663535353735386564373038336334
            6631396335353633343135623434663737326438656165373530623938343939656165610a6335366235626465323
            265373131653166366238323633363333343532353134376465333065633035373965626133613938323839656531
            31663863613436643436636161386364363234613563393033653162343061626134386634326165
    verifier: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            663830383866356263333964643466653064343735336438653166356463653565336166663936646364333032363
            836656230623732643731366165383562340a61313738336339323861363933333635303462653361643933623439
            6232616561333438663133643535386165343030643434646232633266626366313932300a3333306637646163663
            666663561343739393139353565383533316531383730616338633862366262383862306466663864343132343561
            66643938643338323030623432613764636333366631353831663964323764393937306530353731
  manager:
    issuer: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            306233613031663933393533373065353439623433346663663637616261373334386465333763326265303130383
            964396332346266343636326339623231620a65336366653864623239383265663033353038346238323466663233
            3735373463613561653033666533383363663436616636363666623933343633373138630a3561306133313662613
            930316133393234393066313338366432303837376539613830646435633933326663393531623763646430633633
            33666462663938623362303333623631646631333166393732346133663866336136383365343039
    verifier: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              3964663438623066346432346230366366613461393661356465613939393439643338636433623663386330666
              56465393162323035346466303933663066660a3931336631613061303763343166303265313836623939333262
              32306135616631323934306362613563313362393937643162336264396663646436616366350a3963633636343
              5626536343363313231353863663633653561343762336339313435336436313861303438643334333039326234
              3035356362376238313139633938643563623831393764356163656434643537303131663366623262383835
    statlist: !vault |
              $ANSIBLE_VAULT;1.1;AES256
              3330303765316264393031353638623064613363356633366463353665663035323036383864353335333737323
              56465656166636234666262353232363065330a6231356564303034623266633531613161353337306666623431
              38333237343964336663663034373563626338363838336233616231643236376364356662350a3032393765626
              6356632613631646333336131333231636334343835303366616631343939666461666263623435393062356661
              6439356136353965646537323632646238663734313734323030383032663763623836396635326136323133
  mbob:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            396132323461653037356437363166343135663530633939376566653132653636636431656264386538666431343
            966333237623263346532616238663938340a63666138653664323833613761356162366661633630393333613264
            6534646535643966323733663264326330333635346266303164633564643738313239320a6136626231376539326
            563303863346662356638326234646235653566336136643866356239666338646332626437323139326632646662
            33323263313639326534643164663532643864633431323664353233643934646537643164333938
    playground: ''
    staging: ''
    production: ''
    status: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            376266366661323663626332333666323531663034363731353537396332626138323034623966343036333761306
            337333837626637363935666439396134630a30623364343736643466316663316161656237366435363039333233
            6366623135313833353234636332653965383230643865386238386339636239663236660a6138323661653465613
            763396162383536633739383335376331343630313739626233636561363032666364376338323437613838373964
            33643465326465353738333232626336336562663764663335363963653038326163626631373637
  tun:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            396132323461653037356437363166343135663530633939376566653132653636636431656264386538666431343
            966333237623263346532616238663938340a63666138653664323833613761356162366661633630393333613264
            6534646535643966323733663264326330333635346266303164633564643738313239320a6136626231376539326
            563303863346662356638326234646235653566336136643866356239666338646332626437323139326632646662
            33323263313639326534643164663532643864633431323664353233643934646537643164333938
    playground: ''
    staging: ''
    production: ''
    status: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            333366326333396238613462313138376337373133343238663565323732646133613734356431346364396164363
            963393332663839643434326237376131330a39633433323161373836633834626438623132363462306633373035
            3836373461626663373662386635323865333363636236356666393632313866343331660a6539643737643232313
            263333661353732313933323138616339636462613434653065633531626533616166396137356434303030663563
            32623231653738363837613931333131323135393637643633626238643031313330636134656661
  uvh:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            396132323461653037356437363166343135663530633939376566653132653636636431656264386538666431343
            966333237623263346532616238663938340a63666138653664323833613761356162366661633630393333613264
            6534646535643966323733663264326330333635346266303164633564643738313239320a6136626231376539326
            563303863346662356638326234646235653566336136643866356239666338646332626437323139326632646662
            33323263313639326534643164663532643864633431323664353233643934646537643164333938
    playground: ''
    staging: ''
    production: ''
    status: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            366665316231333336353532653735313839333038303730633030646134343761326536336366383038616563653
            363303636353533653237393633633361310a62656134343733303538633832366131646239396434653465373637
            6333653066386635386261363837663435333764313761393466653530313963646566340a6133636136613034633
            834336231613934323865323332303439666638656666393330316538376466313063333663373133626262396462
            31353232333439643538343036383964373531623339626238386535316334366333393138663465
  hbot:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            396132323461653037356437363166343135663530633939376566653132653636636431656264386538666431343
            966333237623263346532616238663938340a63666138653664323833613761356162366661633630393333613264
            6534646535643966323733663264326330333635346266303164633564643738313239320a6136626231376539326
            563303863346662356638326234646235653566336136643866356239666338646332626437323139326632646662
            33323263313639326534643164663532643864633431323664353233643934646537643164333938
    playground: ''
    staging: ''
    production: ''
    status: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            333366326333396238613462313138376337373133343238663565323732646133613734356431346364396164363
            963393332663839643434326237376131330a39633433323161373836633834626438623132363462306633373035
            3836373461626663373662386635323865333363636236356666393632313866343331660a6539643737643232313
            263333661353732313933323138616339636462613434653065633531626533616166396137356434303030663563
            32623231653738363837613931333131323135393637643633626238643031313330636134656661
  nlgov:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            396132323461653037356437363166343135663530633939376566653132653636636431656264386538666431343
            966333237623263346532616238663938340a63666138653664323833613761356162366661633630393333613264
            6534646535643966323733663264326330333635346266303164633564643738313239320a6136626231376539326
            563303863346662356638326234646235653566336136643866356239666338646332626437323139326632646662
            33323263313639326534643164663532643864633431323664353233643934646537643164333938
    playground: ''
    staging: ''
    production: ''
    status: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            663534373762333634323635373134636639376338653566613536616430333435623233633464623330303832306
            639386634363566636237373836386662640a61656236396131356235626133396262316164333366636562346532
            6438383065643561326230653336356362626238646631353062663066316132396464380a3938633637646664646
            436353864613039323639636531323939326635363862323434386235356163646335643732353333613766613961
            31636236303161366362653161313864653362396161353835343362356432356138326266613437
  nbgov:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            396132323461653037356437363166343135663530633939376566653132653636636431656264386538666431343
            966333237623263346532616238663938340a63666138653664323833613761356162366661633630393333613264
            6534646535643966323733663264326330333635346266303164633564643738313239320a6136626231376539326
            563303863346662356638326234646235653566336136643866356239666338646332626437323139326632646662
            33323263313639326534643164663532643864633431323664353233643934646537643164333938
    playground: ''
    staging: ''
    production: ''
    status: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            656631343061653636623232636565333961323736393235396630383839303433656330386233383231616461346
            538636336386265363235393132306537610a31646636373339353330356539636632353232343935383336393465
            3463623837353262663630656134313935383963663239313334393564643938666434390a3766626135666665633
            166653739666531313736336465346430356339326364393138613462313938326133656338313730343537386139
            38663261623836383136353833333136666133343464393239363662633733653930366439393932
  epi:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            396132323461653037356437363166343135663530633939376566653132653636636431656264386538666431343
            966333237623263346532616238663938340a63666138653664323833613761356162366661633630393333613264
            6534646535643966323733663264326330333635346266303164633564643738313239320a6136626231376539326
            563303863346662356638326234646235653566336136643866356239666338646332626437323139326632646662
            33323263313639326534643164663532643864633431323664353233643934646537643164333938
    playground: ''
    staging: ''
    production: ''
    status: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            306135616537333464343166626565346431313430643735306132356630336230623537363564353932633761623
            731336439656565643737333362356636640a32633162316362613165396536663761373833653536656661306461
            3637333732336537653864643435626437346335333235323264326238323731663231620a3835663633353466396
            566333363303934636266643530393637323033373565643539323836623961663461643238353734373434613835
            66323036663131353765333366383636646265656566373538343131393166623133643363376236
  proxy:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            64623034663261353664343137643634383038663630663062343463643664343736373430326636656138663438623
            2646536333137376637326562623033630a346434333962373561316137616539376430323265326461653235333566
            303964653832313630333930356630663930383538343334346638613465383638310a3935366163666537303939636
            56238616462393763633065303763623661333039396363356665343932336464323532356661633664363463306639
            376466663665303263306432383066313264386566383636663038316634363335353631
  sandbox:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            31366530623038653333323636326230346632303533633939363563643662656639646362383332633433366365366
            6323762613065326337303164323435330a383530323561383833326436376262353665303834386334343238396361
            386166346636323037363862383965393336326435363966636265326334383735650a3363333365646561353661656
            63362633138373830306161616139386466653735386630386163346532663464313132383338383637316664343333
            623630383830656166623034313032396134616463303835386330373562393238663239
    playground: ''
    staging: ''
    production: ''
    status: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            34353136666438393832356465666363313964303234383638336264306465376466356337376330656239613738376
            4326266303036323138303938333530620a326434666637333765363962343439616430613430303937303639396663
            663266626266393337613136373837653739666464633464613938383865393131640a3662316438653765346536613
            33032616661653534346234613866373865613165336431323338626330616661383934383065306532666261626363
            653035666239356637356565353961313063306131613464306434353731316261353133
    verAdmin: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            65336536306564646461313366353465343166633036663636343332383233663838636265613931373866623131626
            2346138323330336539626466646162340a633161636331343737636262643337373832663337626230623331383163
            643264303336396134666639393836633035306662323636346138313834383035320a3137366336616439373734343
            36565346531653836333537646631353666393332393033383961323231373064316664303230323836653334386437
            373139323064623264303038643361343237356538336537643338343966623433356434
    verPlayground: ''
    verStaging: ''
    verProduction: ''
  auth:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            61343462663033313964346430306533623738366531623362633230303366366166366539303033643961343036306
            6386661383263613062396265643366640a643462623435653839363734313961633237313465333966333266653331
            313565633830363830336337323232316132633233363930336165313261383438380a3161636438383363386561353
            73232316330626135373837346331356237626630633237323336643330633133396336626161643034653865306439
            303365393130363138393765666664376437376164313161313539343634326633303733
  eduid:
    admin:  !vault |
            $ANSIBLE_VAULT;1.1;AES256
            30323433626561323466313066643663613966386464346631653561613135393539356363623533306566313733326
            3326336303631393432323734343834370a363538343434626564303336333836636564393339353966376237383132
            633861623633323664396133373233346439336362653863313363313239376562620a3237356439326432393836366
            26361656132346134653866373236323863643035656666316361333265383536633961363836356662333334613136
            613039656563643935363039303361323331333365353936386131633163376339346230
    playground: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            35663838633264393761316163356263336439623637383333303262393737643834363864346566333732633665666
            4363533313062383561623930383438390a313661653961653263386366383137306465333937303964613038613633
            626463323266353462656464316638666634626265386334343736363132353965620a6166633563386335613036373
            76562323266323738393663616461333166313830363532653863366132376235336537336136653835303234353039
            396633613634366365653832333864303539333835653162616365393062393833376465
    staging: ''
    production: ''
